### ISSUE TITLE
Add Function to open a website

### ISSUE THREAD

**Issue by PriyanshuPz** [p7uverma/bard-chatbot#1]
**Write an "if" statement to open a website when a user says any keyword in a query.**

**Comment by sukhmani1303** [comment]
I would love to contribute to this issue. Can you elaborate on the issue a little more, please?

**Comment by imkrishnasarathi** [comment]
I would like to contribute to this, but I need to know what website needs to be opened, like more details

**Comment by PriyanshuPz** [comment]
Any website that user wants like:
user says: please open YouTube for me.
user says: open google.com

**Comment by imkrishnasarathi** [comment]
I am a bit busy today. Please wait. I will send a PR by today night if I complete it :)

**Comment by imkrishnasarathi** [comment]
When I run your program:- 
`Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\bard-chatbot\bard.py", line 2, in <module>
    from bardapi import BardCookies
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core.py", line 28, in <module>
    from bardapi.models.result import BardResult
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\draft.py", line 9, in <module>
    from bardapi.models.tools.map import BardMapContent
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py", line 6, in <module>
    class BardMapsPoint:
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py", line 58, in BardMapsPoint
    def title(self) -> Tuple[str, str]:
                       ^^^^^
NameError: name 'Tuple' is not defined. Did you mean: 'tuple'?`

**Comment by imkrishnasarathi** [comment]
If I go ahead and edit the map.py to have `from typing import Tuple`, I get this
```
C:\Users\HP\PycharmProjects\bard-chatbot\venv\Scripts\python.exe C:\Users\HP\PycharmProjects\bard-chatbot\bard.py 
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\bard-chatbot\bard.py", line 2, in <module>
    from bardapi import BardCookies, Bard
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core.py", line 28, in <module>
    from bardapi.models.result import BardResult
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\draft.py", line 9, in <module>
    from bardapi.models.tools.map import BardMapContent
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py", line 124, in <module>
    class BardMapsDirections:
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py", line 141, in BardMapsDirections
    def sections(self) -> List[BardMapsRoadSection]:
                          ^^^^
NameError: name 'List' is not defined. Did you mean: 'list'?

Process finished with exit code 1
```

**Comment by PriyanshuPz** [comment]
See the readme file: 
(Optional) Make changes in .venv\Lib\site-packages\bardapi\core.py if gives any error like requests not found.

add at top:
```python
import requests
```
(Optional) Make changes in ..venv\Lib\site-packages\bardapi\models\tools\map.py if gives any error like Tuple not found.
add at top:

```python
from typing import Optional, Tuple, List
```

**Comment by PriyanshuPz** [comment]
> If I go ahead and edit the map.py to have `from typing import Tuple`, I get this
> 
> ```
> C:\Users\HP\PycharmProjects\bard-chatbot\venv\Scripts\python.exe C:\Users\HP\PycharmProjects\bard-chatbot\bard.py 
> Traceback (most recent call last):
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\bard.py", line 2, in <module>
>     from bardapi import BardCookies, Bard
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\__init__.py", line 4, in <module>
>     from bardapi.core import Bard
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core.py", line 28, in <module>
>     from bardapi.models.result import BardResult
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\result.py", line 3, in <module>
>     from bardapi.models.draft import BardDraft
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\draft.py", line 9, in <module>
>     from bardapi.models.tools.map import BardMapContent
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py", line 124, in <module>
>     class BardMapsDirections:
>   File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py", line 141, in BardMapsDirections
>     def sections(self) -> List[BardMapsRoadSection]:
>                           ^^^^
> NameError: name 'List' is not defined. Did you mean: 'list'?
> 
> Process finished with exit code 1
> ```
do this:
(Optional) Make changes in `C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\models\tools\map.py` if gives any error like Tuple not found.
add at top:
```python
from typing import Optional, Tuple, List
```
@imkrishnasarathi

**Comment by imkrishnasarathi** [comment]
ok thanks. I got a school assignment today, so I couldn't keep my words. I will try to complete it by tmmro noon. Please don't reassign it to anyone :)

**Comment by PriyanshuPz** [comment]
@imkrishnasarathi Not problem. I am also a school student I can understand. I will not unassign you. As we are friends.👏

**Comment by imkrishnasarathi** [comment]
Now this :-
```
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\bard-chatbot\bard.py", line 2, in <module>
    from bardapi import BardCookies, Bard
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core.py", line 39, in <module>
    class Bard:
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core.py", line 49, in Bard
    session: Optional[requests.Session] = None,
                      ^^^^^^^^
NameError: name 'requests' is not defined
```

**Comment by imkrishnasarathi** [comment]
If I import requests in the core.py file, then I get this:-
```
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\bard-chatbot\bard.py", line 33, in <module>
    bard = BardCookies(cookie_dict=bard_dict, language="english")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core_cookies.py", line 53, in __init__
    self.SNlM0e = self._get_snim0e()
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\bard-chatbot\venv\Lib\site-packages\bardapi\core_cookies.py", line 119, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found in response. Check __Secure-1PSID value.
```

**Comment by PriyanshuPz** [comment]
Add .env file. Check readme.md and contributing.md for that @imkrishnasarathi .
You will get token from bard.google.com
In cookies:

**Comment by imkrishnasarathi** [comment]
Ok thanks

**Comment by imkrishnasarathi** [comment]
Done. Submitted a PR

**Comment by sukhmani1303** [comment]
🚨 I don't think the issue is resolved yet... this issue is not just any if-else type of problem as context & sentiment must also be considered. For example; if someone types "I cannot open youtube.com  due to XYZ error. What should I do?" In this case, @imkrishnasarathi 's code will open the website but that was not what the user asked for.
The solution to this issue is relatively comprehensive where you need to identify if the user wants to open a website or wants an answer. This can be solved by either training your own model using custom data (query - answer) which is for this particular task only or using any other pre-trained summarize etc.... & based on its output we can decide if to open a webpage or provide an answer @p7uverma

**Comment by imkrishnasarathi** [comment]
Oh I just did the simple solution for just opening it

**Comment by PriyanshuPz** [comment]
@sukhmani1303 Got you! If you're able to do that try and fix this. I have assigned you this task.

**Comment by sukhmani1303** [comment]
It's a very comprehensive issue actually... will take a lot of time but i will try 👍
